# Generated by Django 5.0.4 on 2024-07-15 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Refeicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alimento', models.CharField(max_length=100)),
                ('quantidade', models.FloatField()),
                ('horario', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='TabelaNutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarioPeso', models.FloatField()),
                ('gorduraCorporal', models.FloatField()),
                ('objetivo', models.CharField(max_length=200)),
                ('exames', models.CharField(max_length=200, null=True)),
                ('refeicoes', models.ManyToManyField(to='galeria.refeicoes')),
                ('usuarioReferencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='galeria.usuario')),
            ],
        ),
    ]
