# Generated by Django 5.0.4 on 2024-08-13 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_delete_administrador_delete_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabelanutricional',
            name='refeicoes',
        ),
    ]
