# Generated by Django 5.0.4 on 2024-08-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_remove_tabelanutricional_refeicoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabelanutricional',
            name='refeicoes',
            field=models.ManyToManyField(to='galeria.refeicoes'),
        ),
    ]
